service: goawsredrive # NOTE: update this with your service name

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  redrive:
    handler: bin/redrive
  manager:
    handler: bin/manager
    events:
      - http:
          path: manager
          method: post