service: goawsredrive # NOTE: update this with your service name

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - "*"
      Resource: 
        - "*"
    

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  redrive:
    handler: bin/redrive
  manager:
    handler: bin/manager
    timeout: 60
    events:
      - http:
          path: manager
          method: post
          cors: true